language: ruby
rvm:
  - 2.1.2
env:
  - DB=sqlite
bundler_args: --without production
cache: bundler
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - RAILS_ENV=test bundle exec rake db:create db:migrate db:fixtures:load
  - bundle exec rackup -p 3000 -E test &
  - sleep 10
script:
  - # bundle exec rake test
  - ls -algt db
  - RAILS_ENV=test bundle exec rake spec
  - ls -algt db
  - bundle exec rake diff_images
