language: ruby
rvm:
  - 2.1.2
env:
  - DB=sqlite
bundler_args: "--without development"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - RAILS_ENV=test bundle exec rake db:drop db:create db:migrate db:fixtures:load
  - RAILS_ENV=test bundle exec rake test
